name: deploy to ec2
on: 
  push:
    branches: main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ec2-user
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /ec2-user/basic_node_app
            git pull
            docker compose up -d --build

            
    