name: basic node app
on:
  push:
    branches:
      - main
    
jobs:
  buils-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4


      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{runner.os}}-node-${{hashFiles('package.json')}}
          restore-keys: |
            ${{runner.os}}-node-

        
      - name: install dependices
        run: npm install
      
      - name: test
        run: npm test
      
      - name: login
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}} 
      
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/basic_node_app:new
